from datetime import datetime
def compare_code(scanned_text, recipe_expected_code):
    """
    Compares the text scanned from the product label against the 
    expected reference code generated by the selected recipe.
    
    Args:
        scanned_text (str): The code read by the scanner/sensor at inspection time.
        recipe_expected_code (str): The reference code returned by the recipe script.
        
    Returns:
        dict: A dictionary containing the boolean result and a status message.
    """
    # Clean up whitespace and newlines for accurate comparison
    scanned = str(scanned_text).strip() if scanned_text else ""
    expected = str(recipe_expected_code).strip() if recipe_expected_code else ""

    result= {
        "status": "NOK",
        "reason": "CODE_MISMATCH",
        "text": scanned,
        "confidence": 100,
        "inspected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
        }
    
    # If the recipe failed to extract anything
    if not expected:
        return {
        "status": "NOK",
        "reason": "RECIPE_READ_FAILED",
        "text": "",
        "confidence": 0,
        "inspected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
        }
        
    # If the scanner failed to read anything
    if not scanned:
        return {
        "status": "NOK",
        "reason": "SCANNER_READ_FAILED",
        "text": "",
        "confidence": 0,
        "inspected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
        }
        
    # Perform exact match comparison
    if scanned == expected:
        return {
           "status": "OK",
            "reason": "CODE_MATCHED",
            "text": scanned,
            "confidence": 100,
            "inspected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
        }
    else:
        return result

print(compare_code('8838838838838', '8838838838838'))
print(compare_code('', '8838838838838')) 
print(compare_code('8838838838838', ''))
print(compare_code('8838838838838', '8838838838839'))
